apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-it-com-wildcard
  namespace: gateway
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  secretName: kube-it-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.kube.it.com"
  dnsNames:
    - "*.kube.it.com"
    - "kube.it.com"