apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: "Layer 3: Business workloads"
  sourceRepos:
    - "*"
  destinations:
    - server: "*"
      namespace: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
