apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 22.2.2
    helm:
      values: |
        replicaCount: 1
        auth:
          adminUser: admin
        proxy: edge
        httpRelativePath: "/"
        postgresql:
          enabled: true
          primary:
            persistence:
              enabled: true
              storageClass: longhorn
              size: 8Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true