apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: keycloak-initial-admin
  namespace: keycloak-system
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: doppler
      kind: ClusterSecretStore
  selector:
    secret:
      name: keycloak-initial-admin
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: KEYCLOAK_ADMIN_USERNAME
    - match:
        secretKey: password
        remoteRef:
          remoteKey: KEYCLOAK_ADMIN_PASSWORD