apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: rabbitmq-default-user
  namespace: rabbitmq
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: doppler
      kind: ClusterSecretStore
  selector:
    secret:
      name: rabbitmq-default-user
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: RABBITMQ_DEFAULT_USERNAME
    - match:
        secretKey: password
        remoteRef:
          remoteKey: RABBITMQ_DEFAULT_PASSWORD
    - match:
        secretKey: host
        remoteRef:
          remoteKey: RABBITMQ_HOST
    - match:
        secretKey: port
        remoteRef:
          remoteKey: RABBITMQ_PORT