apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq-cluster-operator
    targetRevision: 4.3.18
    helm:
      values: |
        clusterOperator:
          replicaCount: 1
        msgTopologyOperator:
          enabled: true
          replicaCount: 1
        useCertManager: true
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true