apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-experimental-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    path: config/crd/experimental
    targetRevision: v1.2.1
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true