apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-experimental-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    path: config/crd/experimental
    targetRevision: v1.2.1
    kustomize:
      patches:
        - target:
            group: apiextensions.k8s.io
            version: v1
            kind: CustomResourceDefinition
            name: backendtlspolicies.gateway.networking.k8s.io
          patch: |
            $patch: delete
            apiVersion: apiextensions.k8s.io/v1
            kind: CustomResourceDefinition
            metadata:
              name: backendtlspolicies.gateway.networking.k8s.io
        - target:
            group: apiextensions.k8s.io
            version: v1
            kind: CustomResourceDefinition
            name: backendlbpolicies.gateway.networking.k8s.io
          patch: |
            $patch: delete
            apiVersion: apiextensions.k8s.io/v1
            kind: CustomResourceDefinition
            metadata:
              name: backendlbpolicies.gateway.networking.k8s.io
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
