apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://charts.min.io
    chart: minio
    targetRevision: 5.2.0
    helm:
      values: |
        mode: standalone
        persistence:
          enabled: true
          storageClass: longhorn
          size: 20Gi
        service:
          type: ClusterIP
        consoleService:
          type: ClusterIP
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: "1"
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
