apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 14.6.15
    helm:
      values: |
        mode: standalone
        persistence:
          enabled: true
          storageClass: longhorn
          size: 20Gi
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true