apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: doppler
      kind: ClusterSecretStore
  selector:
    secret:
      name: minio
  data:
    - match:
        secretKey: rootUser
        remoteRef:
          remoteKey: MINIO_ROOT_USER
    - match:
        secretKey: rootPassword
        remoteRef:
          remoteKey: MINIO_ROOT_PASSWORD