apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: keycloak-db-credentials
    creationPolicy: Owner
    template:
      data:
        username: keycloak
        database: keycloak
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: KEYCLOAK_DB_PASSWORD