apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://charts.releases.teleport.dev
    chart: teleport-cluster
    targetRevision: 18.7.3
    helm:
      values: |
        clusterName: teleport.kube.it.com

        acme: false

        tls:
          existingSecretName: teleport-tls

        service:
          type: LoadBalancer

        persistence:
          enabled: true
          storageClassName: longhorn
          size: 10Gi

        proxyListenerMode: separate

        publicAddr:
          - teleport.kube.it.com:443

        sshPublicAddr:
          - teleport.kube.it.com:3023

        tunnelPublicAddr:
          - teleport.kube.it.com:3024

        kubePublicAddr:
          - teleport.kube.it.com:3026

        authentication:
          type: local
          secondFactors:
            - otp
            - webauthn

        auth:
          teleportConfig:
            auth_service:
              authentication:
                webauthn:
                  rp_id: teleport.kube.it.com
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true