apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: teleport
  namespace: teleport
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: teleport
  validation:
    wellKnownCACertificates: System
    hostname: teleport.kube.it.com
