apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: teleport
  namespace: teleport
spec:
  parentRefs:
    - name: shared-gateway
      namespace: gateway
      sectionName: teleport-passthrough
  hostnames:
    - teleport.kube.it.com
  rules:
    - backendRefs:
        - name: teleport
          port: 3080